import { CruiseStats, Ticket, Language, Category } from '../types';

export interface CruiseReportOptions {
  language: Language;
  since?: number;
  until?: number;
  useLLM?: boolean;
  llmClient?: any;
}

const reportTitles: Record<Language, string> = {
  'zh-CN': '客诉巡航报告',
  'zh-TW': '客訴巡航報告',
  'en': 'Ticket Cruise Report',
  'ja': 'チケット巡航レポート',
  'ko': '티켓 순회 보고서',
  'es': 'Informe de Crucero de Tickets',
  'unknown': 'Ticket Cruise Report'
};

const execSummaryLabels: Record<Language, { total: string; highPriority: string }> = {
  'zh-CN': { total: '统计客诉', highPriority: '高优先级' },
  'zh-TW': { total: '統計客訴', highPriority: '高優先級' },
  'en': { total: 'Total Tickets', highPriority: 'High Priority' },
  'ja': { total: '総チケット数', highPriority: '高優先度' },
  'ko': { total: '총 티켓', highPriority: '높은 우선순위' },
  'es': { total: 'Total de Tickets', highPriority: 'Alta Prioridad' },
  'unknown': { total: 'Total Tickets', highPriority: 'High Priority' }
};

const sectionLabels: Record<Language, { langDist: string; catStats: string }> = {
  'zh-CN': { langDist: '语言分布', catStats: '分类统计' },
  'zh-TW': { langDist: '語言分佈', catStats: '分類統計' },
  'en': { langDist: 'Language Distribution', catStats: 'Category Statistics' },
  'ja': { langDist: '言語分布', catStats: 'カテゴリ統計' },
  'ko': { langDist: '언어 분포', catStats: '카테고리 통계' },
  'es': { langDist: 'Distribución de Idiomas', catStats: 'Estadísticas de Categorías' },
  'unknown': { langDist: 'Language Distribution', catStats: 'Category Statistics' }
};

const tableHeaders: Record<Language, { lang: string; count: string; pct: string; category: string }> = {
  'zh-CN': { lang: '语言', count: '数量', pct: '占比', category: '类别' },
  'zh-TW': { lang: '語言', count: '數量', pct: '佔比', category: '類別' },
  'en': { lang: 'Language', count: 'Count', pct: 'Percentage', category: 'Category' },
  'ja': { lang: '言語', count: '件数', pct: '割合', category: 'カテゴリ' },
  'ko': { lang: '언어', count: '수량', pct: '비율', category: '카테고리' },
  'es': { lang: 'Idioma', count: 'Cantidad', pct: 'Porcentaje', category: 'Categoría' },
  'unknown': { lang: 'Language', count: 'Count', pct: 'Percentage', category: 'Category' }
};

export function generateCruiseReport(
  tickets: Ticket[],
  stats: CruiseStats,
  options: CruiseReportOptions
): string {
  const { language } = options;
  const labels = execSummaryLabels[language];
  const sections = sectionLabels[language];
  const headers = tableHeaders[language];
  
  const lines: string[] = [];
  lines.push(`# ${reportTitles[language]} — ${formatDateCN(Date.now())}`);
  lines.push('');
  lines.push(`## ${language === 'en' ? 'Executive Summary' : sections.langDist.replace('语言分布', '执行摘要').replace('語言分佈', '執行摘要')}`);
  lines.push(`- ${labels.total}: ${stats.total} ${language === 'zh-CN' || language === 'zh-TW' ? '条' : ''}`);
  lines.push(`- ${labels.highPriority}: ${stats.highPriority} ${language === 'zh-CN' || language === 'zh-TW' ? '条' : ''}`);
  lines.push('');
  
  // Language distribution section title
  lines.push(`## ${sections.langDist}`);
  lines.push(`| ${headers.lang} | ${headers.count} | ${headers.pct} |`);
  lines.push('|------|------|------|');
  for (const [lang, count] of Object.entries(stats.languages)) {
    const percentage = stats.total > 0 ? ((count / stats.total) * 100).toFixed(1) : '0.0';
    lines.push(`| ${getLanguageName(lang, language)} | ${count} | ${percentage}% |`);
  }
  lines.push('');
  
  // Category statistics section
  lines.push(`## ${sections.catStats}`);
  lines.push(`| ${headers.category} | ${headers.count} | ${headers.pct} |`);
  lines.push('|------|------|------|');
  for (const [cat, count] of Object.entries(stats.categories)) {
    const percentage = stats.total > 0 ? ((count / stats.total) * 100).toFixed(1) : '0.0';
    const icon = getCategoryIcon(cat as Category);
    lines.push(`| ${icon} ${getCategoryName(cat as Category, language)} | ${count} | ${percentage}% |`);
  }
  lines.push('');
  
  // 页脚
  lines.push('---');
  lines.push(`Generated by Community Manager Agent Spine v0.5.0`);
  
  return lines.join('\n');
}

export function calculateCruiseStats(tickets: Ticket[]): CruiseStats {
  const stats: CruiseStats = {
    total: tickets.length,
    categories: {} as Record<Category, number>,
    languages: {} as Record<Language, number>,
    highPriority: 0
  };
  
  for (const ticket of tickets) {
    stats.categories[ticket.category] = (stats.categories[ticket.category] || 0) + 1;
    if (ticket.detected_language) {
      stats.languages[ticket.detected_language] = (stats.languages[ticket.detected_language] || 0) + 1;
    }
    if (ticket.severity === 'high' || ticket.severity === 'critical') {
      stats.highPriority++;
    }
  }
  
  return stats;
}

function formatDateCN(timestamp: number): string {
  const date = new Date(timestamp);
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')} ${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`;
}

function getLanguageName(lang: string, displayLanguage: Language): string {
  const names: Record<string, Record<string, string>> = {
    'zh-CN': { 'zh-CN': '简体中文', 'zh-TW': '繁体中文', 'en': '英文', 'ja': '日文', 'ko': '韩文', 'es': '西班牙文' },
    'en': { 'zh-CN': 'Simplified Chinese', 'zh-TW': 'Traditional Chinese', 'en': 'English', 'ja': 'Japanese', 'ko': 'Korean', 'es': 'Spanish' }
  };
  return names[displayLanguage]?.[lang] || lang;
}

function getCategoryIcon(category: Category): string {
  const icons: Record<Category, string> = {
    'payment': '💰',
    'refund': '🔄',
    'bug': '🐛',
    'ban_appeal': '🔒',
    'abuse': '⚠️',
    'general': '📝'
  };
  return icons[category] || '❓';
}

function getCategoryName(category: Category, language: Language): string {
  const names: Partial<Record<Language, Record<Category, string>>> = {
    'zh-CN': {
      'payment': '充值/支付',
      'refund': '退款',
      'bug': '游戏Bug',
      'ban_appeal': '封号申诉',
      'abuse': '举报/作弊',
      'general': '其他'
    },
    'en': {
      'payment': 'Payment',
      'refund': 'Refund',
      'bug': 'Bug',
      'ban_appeal': 'Ban Appeal',
      'abuse': 'Abuse',
      'general': 'General'
    }
  };
  return names[language]?.[category] || category;
}
