import { CruiseStats, Ticket, Category, Language } from '../types';
import { getReportTitles, getCategoryIcon, getCategoryName, getLanguageName } from '../i18n/reports';
import { formatDateCN } from './formatters';

export interface CruiseReportOptions {
    language: Language;  // 报告输出语言
    since?: number;      // 起始时间戳
    until?: number;      // 结束时间戳
}

/**
 * 生成巡航报告
 * @param tickets 客诉列表
 * @param stats 统计数据
 * @param options 选项
 * @returns Markdown 格式报告
 */
export function generateCruiseReport(
    tickets: Ticket[],
    stats: CruiseStats,
    options: CruiseReportOptions
): string {
    const { language } = options;
    
    // 使用 i18n/reports.ts 获取本地化标题
    const titles = getReportTitles(language);
    
    const lines: string[] = [];
    
    // 标题
    lines.push(`# ${titles.title} — ${formatDateCN(Date.now())}`);
    lines.push('');
    
    // 执行摘要
    lines.push(`## ${titles.summary}`);
    lines.push(`- ${titles.totalTickets}: ${stats.total}`);
    lines.push(`- ${titles.highPriority}: ${stats.highPriority}`);
    lines.push('');
    
    // 语言分布
    lines.push(`## ${titles.languageDistribution}`);
    lines.push('| 语言 | 数量 | 占比 |');
    lines.push('|------|------|------|');
    for (const [lang, count] of Object.entries(stats.languages)) {
        const percentage = ((count / stats.total) * 100).toFixed(1);
        lines.push(`| ${getLanguageName(lang, language)} | ${count} | ${percentage}% |`);
    }
    lines.push('');
    
    // 分类统计
    lines.push(`## ${titles.categoryStats}`);
    lines.push('| 类别 | 数量 | 占比 | 高优先级 |');
    lines.push('|------|------|------|---------|');
    for (const [cat, count] of Object.entries(stats.categories)) {
        const percentage = ((count / stats.total) * 100).toFixed(1);
        const icon = getCategoryIcon(cat as Category);
        lines.push(`| ${icon} ${getCategoryName(cat as Category, language)} | ${count} | ${percentage}% | - |`);
    }
    lines.push('');
    
    // 高优先级队列
    const highPriorityTickets = tickets.filter(t => t.severity === 'high' || t.severity === 'critical');
    if (highPriorityTickets.length > 0) {
        lines.push(`## ${titles.highPriorityQueue}`);
        lines.push('| ID | 语言 | 类别 | 内容摘要 |');
        lines.push('|----|------|------|---------|');
        for (const ticket of highPriorityTickets.slice(0, 10)) {
            const summary = ticket.text.substring(0, 30) + (ticket.text.length > 30 ? '...' : '');
            lines.push(`| ${ticket.id} | ${ticket.detected_language || '-'} | ${ticket.category} | ${summary} |`);
        }
        lines.push('');
    }
    
    // 页脚
    lines.push('---');
    lines.push(`Generated by Community Manager Agent Spine v0.5.0`);
    
    return lines.join('\n');
}

/**
 * 计算巡航统计
 */
export function calculateCruiseStats(tickets: Ticket[]): CruiseStats {
    const stats: CruiseStats = {
        total: tickets.length,
        categories: {} as Record<Category, number>,
        languages: {} as Record<Language, number>,
        highPriority: 0
    };
    
    for (const ticket of tickets) {
        // 分类统计
        stats.categories[ticket.category] = (stats.categories[ticket.category] || 0) + 1;
        
        // 语言统计
        if (ticket.detected_language) {
            stats.languages[ticket.detected_language] = (stats.languages[ticket.detected_language] || 0) + 1;
        }
        
        // 高优先级计数
        if (ticket.severity === 'high' || ticket.severity === 'critical') {
            stats.highPriority++;
        }
    }
    
    return stats;
}
